### Pytorch Basics

In [2]:
import torch

torch.__version__

'2.2.2+cpu'

#### Reshaping , Viewing, Stacking, Squeeze, Unsqueeze, and Permute Tensors

1. Reshaping --> ``` Changes an input tensor to a defined shape ```
2. View --> ``` Return a view of an inout tensor of certain shape but shares the same memory as the orignal tensor ```
3. Stacking --> ```Combing  multiple tensor on-top of eachother ```
4. Squeeze --> ``` Removes all `1` dimensions from a tensor ```
5. Unsqueeze --> ``` add a `1` dimension to a target tensor ```
6. Permute --> ``` Return a view of the input with dimensions swapped in a certain way```

In [53]:
#creating a tensor
x= torch.arange(start=1, end=10, step=0.5, dtype=(torch.float32))

In [54]:
x, x.shape

(tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
         5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000]),
 torch.Size([18]))

In [55]:
#reshaping
x_reshape = x.reshape(6,3)
x_reshape

tensor([[1.0000, 1.5000, 2.0000],
        [2.5000, 3.0000, 3.5000],
        [4.0000, 4.5000, 5.0000],
        [5.5000, 6.0000, 6.5000],
        [7.0000, 7.5000, 8.0000],
        [8.5000, 9.0000, 9.5000]])

In [56]:
#reshaping aagain
x_reshape = x.reshape(9,2)
x_reshape

tensor([[1.0000, 1.5000],
        [2.0000, 2.5000],
        [3.0000, 3.5000],
        [4.0000, 4.5000],
        [5.0000, 5.5000],
        [6.0000, 6.5000],
        [7.0000, 7.5000],
        [8.0000, 8.5000],
        [9.0000, 9.5000]])

In [57]:
#changing a view
z= x.view(9,2)
z.shape

torch.Size([9, 2])

In [58]:
z @ x_reshape.T

tensor([[  3.2500,   5.7500,   8.2500,  10.7500,  13.2500,  15.7500,  18.2500,
          20.7500,  23.2500],
        [  5.7500,  10.2500,  14.7500,  19.2500,  23.7500,  28.2500,  32.7500,
          37.2500,  41.7500],
        [  8.2500,  14.7500,  21.2500,  27.7500,  34.2500,  40.7500,  47.2500,
          53.7500,  60.2500],
        [ 10.7500,  19.2500,  27.7500,  36.2500,  44.7500,  53.2500,  61.7500,
          70.2500,  78.7500],
        [ 13.2500,  23.7500,  34.2500,  44.7500,  55.2500,  65.7500,  76.2500,
          86.7500,  97.2500],
        [ 15.7500,  28.2500,  40.7500,  53.2500,  65.7500,  78.2500,  90.7500,
         103.2500, 115.7500],
        [ 18.2500,  32.7500,  47.2500,  61.7500,  76.2500,  90.7500, 105.2500,
         119.7500, 134.2500],
        [ 20.7500,  37.2500,  53.7500,  70.2500,  86.7500, 103.2500, 119.7500,
         136.2500, 152.7500],
        [ 23.2500,  41.7500,  60.2500,  78.7500,  97.2500, 115.7500, 134.2500,
         152.7500, 171.2500]])

In [59]:
x

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [60]:
z

tensor([[1.0000, 1.5000],
        [2.0000, 2.5000],
        [3.0000, 3.5000],
        [4.0000, 4.5000],
        [5.0000, 5.5000],
        [6.0000, 6.5000],
        [7.0000, 7.5000],
        [8.0000, 8.5000],
        [9.0000, 9.5000]])

In [61]:
#changing the first index
z[:, 0] =5

In [65]:
x[0]

tensor(5.)

In [77]:
#working with stacks
x_stacked= torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5.0000, 5.0000, 5.0000, 5.0000],
        [1.5000, 1.5000, 1.5000, 1.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [2.5000, 2.5000, 2.5000, 2.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [3.5000, 3.5000, 3.5000, 3.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [4.5000, 4.5000, 4.5000, 4.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [5.5000, 5.5000, 5.5000, 5.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [6.5000, 6.5000, 6.5000, 6.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [7.5000, 7.5000, 7.5000, 7.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [8.5000, 8.5000, 8.5000, 8.5000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [9.5000, 9.5000, 9.5000, 9.5000]])

In [89]:
#working with squeeze
x_reshape=x_reshape.reshape(1,-1)
print('Reshaped Tensore',x_reshape.shape)

Reshaped Tensore torch.Size([1, 18])


In [88]:
print('Working with Squeeze: ',x_reshape.squeeze().shape)

Working with Squeeze:  torch.Size([18])


In [93]:
#rworking with unsqueeze
print('Unsqueeze:', x_reshape.unsqueeze(dim=0).shape)

Unsqueeze: torch.Size([1, 1, 18])


In [111]:
#working with torch permute
z= torch.randn(size=(224,324,3)) ##height--0 , width-- 1 color --2

print('Z shaped:', z.shape)
#arranging the axis or dims ordr it takes the index 
z_prermute=torch.permute(z, (1,2,0))
print('Z permuted:',z_prermute.shape)

Z shaped: torch.Size([224, 324, 3])
Z permuted: torch.Size([324, 3, 224])


#### Tensor Indexing

In [125]:
#1,3,3 --> 1 *3 *3
a= torch.arange(1,10).reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [133]:
#accessing the first dimesion
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [129]:
a[0][2][2]

tensor(9)

In [143]:
a[:, 1,1]

tensor([5])

In [154]:
a[:,2,2]

tensor([9])

In [159]:
#accessing the 2 index of the column rows
a[:, :, 2]

tensor([[3, 6, 9]])

#### Pytorch and Numpy

In [160]:
import numpy as np

In [167]:
#from numpy to torch
array = np.arange(1,9)
tensor = torch.from_numpy(array).type(torch.half)
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float16),
 array([1, 2, 3, 4, 5, 6, 7, 8]))

In [169]:
array= array +1
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
tensor= torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [174]:
#from torch to numpy
numpy_tensor = tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Reproducibility

We need to reduce the reproduciblity of neural networks with random seeds

In [175]:
rand_tensor_A = torch.randn(3,4)
rand_tensor_B = torch.randn(3,4)



rand_tensor_A == rand_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [179]:
#setting the random seeds
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)

rand_tensor_C = torch.randn(3,4)

torch.manual_seed(RANDOM_SEED)

rand_tensor_D = torch.randn(3,4)



rand_tensor_C == rand_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])