### Pytorch Basics

In [2]:
import torch
#displaying the pytorch version
print(torch.__version__)

2.2.2+cpu


#### Introduction to Tensors

Ways to represent multi dimensional data

In [3]:
#scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
#checking the dimesion and shape
scaler.ndim, scaler.shape

(0, torch.Size([]))

In [5]:
#getting the item back
scaler.item()

7

In [6]:
#creating a vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [7]:
#checking the dimesion and shape
vector.ndim , vector.shape


(1, torch.Size([2]))

In [8]:
#creating a matrix
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
#checking the dimesion and shape
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [10]:
#creating a Tensor
TENSOR = torch.tensor(
    [
        [
            [1,2,3], 
            [3,56,78],
            [2,6,4]
        ]
    ]
)
TENSOR

tensor([[[ 1,  2,  3],
         [ 3, 56, 78],
         [ 2,  6,  4]]])

In [11]:
#checking the dimesion and shape
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

#### Random Tensors

Why Random Tensors?
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` Start with random numbers -> look at data -> update the random numbers -> look at data -> update random numbers


In [12]:
#creating a ranom tensor of size and shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3668, 0.7238, 0.1442, 0.6681],
        [0.1086, 0.8777, 0.8337, 0.3112],
        [0.7618, 0.4906, 0.2212, 0.6980]])

In [13]:
#checking the dimension
random_tensor.ndim

2

In [14]:
#creating a ranodm tensor with similar shape to an image
#size= (height, width, color channels(R,G,B)) color channels

random_image_size_tensor = torch.rand(
    size=(3,224,224)
)

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Creating Torch Zeros and Ones

In [15]:
#creating a tensor of zeros
zeros = torch.zeros(size=(3,4), dtype=int)
zeros 

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [16]:
#creating a tensor of ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a Range and Tensor Like

In [17]:
#start end and step
range_val = torch.arange(start=1, end=10, step=4)
range_val

tensor([1, 5, 9])

In [18]:
#creating tensors like of ones and zeros
one_like,  zero_like = torch.ones_like(range_val), torch.zeros_like(ones)
one_like, zero_like

(tensor([1, 1, 1]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

#### Tensor Data-types
Issues:
1. Tensors not right data-type.
2. Tensor not right right shape.
3. Tensor not on the right device.

In [19]:
#creaing a default data-type
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=None,  #data-type e.g (float 32, int64)
                 device='cpu',  #
                 requires_grad=False #whether or not you want to track gradients with this tensors operations
)

#data-type
float_32_tensor.dtype

torch.float32

In [20]:
#converting  float 32 to float 16
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
#multiply the two data-types
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [22]:
int_16_tensor= float_32_tensor.type(torch.int16)
int_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

In [23]:
#multiplying the different data-types
int_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting Information from Tensors via Attributes

Topics
1. dtype -> data-type
2. device-> operating system
3. shape-> Dimension

In [26]:
#creating a random tensor
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.4337, 0.6493, 0.9724, 0.9297],
        [0.7583, 0.4473, 0.5276, 0.7732],
        [0.3486, 0.6721, 0.6264, 0.8748]])

In [34]:
#getting detailed info
print('Data type',rand_tensor.dtype)
print('Shape of Tensor',rand_tensor.shape)
print('Device:', rand_tensor.device)

Data type torch.float32
Shape of Tensor torch.Size([3, 4])
Device: cpu


#### Tensors Operations
Topics
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [42]:
#creating a tensor
tensor = torch.tensor([1,2,3])
#perfroming additiion
tensor =tensor + 10
tensor

tensor([11, 12, 13])

In [41]:
#perfroming multiplication
tensor * 10

tensor([110, 120, 130])

In [43]:
#subtracting
tensor-10

tensor([1, 2, 3])

In [45]:
#square root and easy multiplication
torch.sqrt(tensor), torch.mul(tensor,10)

(tensor([3.3166, 3.4641, 3.6056]), tensor([110, 120, 130]))

In [48]:
#Elemenat wise Multiplication
print('Element Wise Multiplication',tensor * tensor)

Element Wise Multiplication tensor([121, 144, 169])


### Matrix Multiplication
You can either use matmul or @

In [88]:
%%time
#matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor(434)
CPU times: total: 0 ns
Wall time: 507 µs


### Lets Compare the Speed

In [77]:
%%time

#perfroming matrix multiplication by hand with for loop
tot = 0

for idx, val in enumerate(tensor):
    tot+=val * val

print(tot)

tensor(434)
CPU times: total: 0 ns
Wall time: 1.01 ms


### Part 2

Common Erros in Deep Leanring
1. Shape errors when multiplying matrices

To Fix:
1. The Inner dimensions must match
   (3,2) @ (3,2) ``` won't work
   (2,3) @ (3,2) ``` will work
2. The Resulting Matrix has the shape of the outer dimension
   (2,3) @ (3,2) --> (2,2)

In [101]:
torch.rand(4,2) @ torch.rand(4,2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x2 and 4x2)

In [102]:
torch.rand(5,3) @ torch.rand(3,5)

tensor([[0.9467, 1.2889, 1.1405, 1.0852, 0.7650],
        [0.5545, 0.7352, 0.6454, 0.6168, 0.4426],
        [1.1758, 1.7460, 1.7076, 1.7729, 1.0707],
        [0.5698, 0.7995, 0.7426, 0.7424, 0.4857],
        [0.6439, 0.8971, 0.8724, 0.9263, 0.5732]])

In [106]:
#shapes for matrix multiplication

tensor_A = torch.tensor(
    [
        [1,4],
        [5,6],
        [9,10]
    ]
)

tensor_B = torch.tensor(
    [
        [7,8],
        [0,3],
        [11,13]
    ]
)


tensor_A @ tensor_B


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [107]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

They have the same dimensions. To fix the issue you can manipultae the shape of one of the tensors using transpose. T(For Transpose)

In [111]:
#shapes for matrix multiplication

tensor_A = torch.tensor(
    [
        [1,4],
        [5,6],
        [9,10]
    ]
)

tensor_B = torch.tensor(
    [
        [7,8],
        [0,3],
        [11,13]
    ]
)


tensor_A @ tensor_B.T


tensor([[ 39,  12,  63],
        [ 83,  18, 133],
        [143,  30, 229]])

In [121]:
#original shapes
print(f'Original Shape tensor A {tensor_A.shape}', f' Tensr B {tensor_B.shape}')
print(f'New  Shape tensor A {tensor_A.shape}', f' Tensr B {tensor_B.T.shape}')
print('Multiplying--------------------------------------------------------------------------')
output= tensor_A @ tensor_B.T
print(f'Output: {output}')

Original Shape tensor A torch.Size([3, 2])  Tensr B torch.Size([3, 2])
New  Shape tensor A torch.Size([3, 2])  Tensr B torch.Size([2, 3])
Multiplying--------------------------------------------------------------------------
Output: tensor([[ 39,  12,  63],
        [ 83,  18, 133],
        [143,  30, 229]])


### Tensor Aggregations
Finding:
1. Min
2. Max
3. Sum
4. etc

In [137]:
#creating a tensor
x= torch.arange(start=-10, end=-100, step=-10)
#finding the min & max
torch.min(x), torch.max(x)

(tensor(-90), tensor(-10))

In [138]:
torch.mean(x.type(torch.float64))

tensor(-50., dtype=torch.float64)

In [139]:
torch.sum(x)

tensor(-450)

In [140]:
torch.argmin(x)

tensor(8)

#### Finding Positonal Min and Max of Tensors

In [146]:
y= torch.arange(start=2,end=120, step=12)

In [150]:
#finding the index of the min and max
torch.argmax(y), torch.argmin(y)

(tensor(9), tensor(0))

DAY 1 End!