### Pytorch Basics

In [2]:
import torch
#displaying the pytorch version
print(torch.__version__)

2.2.2+cpu


#### Introduction to Tensors

Ways to represent multi dimensional data

In [3]:
#scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
#checking the dimesion and shape
scaler.ndim, scaler.shape

(0, torch.Size([]))

In [5]:
#getting the item back
scaler.item()

7

In [6]:
#creating a vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [7]:
#checking the dimesion and shape
vector.ndim , vector.shape


(1, torch.Size([2]))

In [8]:
#creating a matrix
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
#checking the dimesion and shape
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [10]:
#creating a Tensor
TENSOR = torch.tensor(
    [
        [
            [1,2,3], 
            [3,56,78],
            [2,6,4]
        ]
    ]
)
TENSOR

tensor([[[ 1,  2,  3],
         [ 3, 56, 78],
         [ 2,  6,  4]]])

In [11]:
#checking the dimesion and shape
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

#### Random Tensors

Why Random Tensors?
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` Start with random numbers -> look at data -> update the random numbers -> look at data -> update random numbers


In [12]:
#creating a ranom tensor of size and shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7826, 0.9685, 0.7513, 0.7283],
        [0.3535, 0.8537, 0.4305, 0.5636],
        [0.1699, 0.3095, 0.7390, 0.5042]])

In [13]:
#checking the dimension
random_tensor.ndim

2

In [14]:
#creating a ranodm tensor with similar shape to an image
#size= (height, width, color channels(R,G,B)) color channels

random_image_size_tensor = torch.rand(
    size=(3,224,224)
)

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Creating Torch Zeros and Ones

In [15]:
#creating a tensor of zeros
zeros = torch.zeros(size=(3,4), dtype=int)
zeros 

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [16]:
#creating a tensor of ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a Range and Tensor Like

In [17]:
#start end and step
range_val = torch.arange(start=1, end=10, step=4)
range_val

tensor([1, 5, 9])

In [18]:
#creating tensors like of ones and zeros
one_like,  zero_like = torch.ones_like(range_val), torch.zeros_like(ones)
one_like, zero_like

(tensor([1, 1, 1]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

#### Tensor Data-types
Issues:
1. Tensors not right data-type.
2. Tensor not right right shape.
3. Tensor not on the right device.

In [19]:
#creaing a default data-type
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=None,  #data-type e.g (float 32, int64)
                 device='cpu',  #
                 requires_grad=False #whether or not you want to track gradients with this tensors operations
)

#data-type
float_32_tensor.dtype

torch.float32

In [20]:
#converting  float 32 to float 16
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
#multiply the two data-types
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [22]:
int_16_tensor= float_32_tensor.type(torch.int16)
int_16_tensor

tensor([3, 6, 9], dtype=torch.int16)

In [23]:
#multiplying the different data-types
int_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

DAY 1 End!